# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'verbose_name': 'Meal', 'verbose_name_plural': 'Meals'},
        ),
    ]
