# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-19 04:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0003_auto_20161127_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
